#!/bin/bash
# Room-first UX (tier-0): room start (auto-default + password + auto code),
# room stop (keep room, release code), room start again (reopen), room delete,
# --open rooms, comma/--all expose, status shapes. Uses the REAL rendezvous
# worker served locally. Scratch everything.
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"; REPO="$(dirname "$DIR")"
WORK=$(mktemp -d)
PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ✗ $1"; }

RDV_PORT=7479; HUB_PORT=7477; HUB_FED=7478; SPOKE_PORT=7476
HUBHOME="$WORK/hub"; SPOKEHOME="$WORK/spoke"; mkdir -p "$HUBHOME/.claude" "$SPOKEHOME/.claude"

cat > "$WORK/rdv.mjs" << EOF
import http from "node:http"; import worker from "$REPO/rendezvous/worker.js";
const s=new Map(); const env={RDV:{async get(k,t){const e=s.get(k);if(!e)return null;if(e.exp&&Date.now()>e.exp){s.delete(k);return null;}return t==="json"?JSON.parse(e.v):e.v;},async put(k,v,o={}){s.set(k,{v,exp:o.expirationTtl?Date.now()+o.expirationTtl*1000:null});},async delete(k){s.delete(k);}}};
http.createServer(async(q,r)=>{let b="";for await(const c of q)b+=c;const x=await worker.fetch(new Request("https://x.local"+q.url,{method:q.method,headers:{"CF-Connecting-IP":"127.0.0.1","Content-Type":"application/json"},body:b||undefined}),env);r.writeHead(x.status);r.end(await x.text());}).listen($RDV_PORT,"127.0.0.1",()=>console.log("up"));
EOF
node "$WORK/rdv.mjs" >/dev/null 2>&1 & RDV=$!
sleep 1
mkdir -p "$WORK/bin"
printf '#!/bin/bash\n( echo "listening at bore.pub:33333" )\nexec sleep 300\n' > "$WORK/bin/bore"; chmod +x "$WORK/bin/bore"

hub()   { HOME="$HUBHOME" CC_BRIDGE_PORT=$HUB_PORT CC_BRIDGE_FED_PORT=$HUB_FED CC_BRIDGE_ROOMS_FILE="$WORK/h.rooms" \
          CC_BRIDGE_RENDEZVOUS="http://127.0.0.1:$RDV_PORT" CC_BRIDGE_CODES_FILE="$WORK/h.codes" CC_BRIDGE_ROOM_KEY_FILE="$WORK/h.rk" \
          CC_BRIDGE_TUNNEL_PID="$WORK/h-t.pid" CC_BRIDGE_TUNNEL_URL="$WORK/h-t.url" CC_BRIDGE_TUNNEL_LOG="$WORK/h-t.log" \
          CC_BRIDGE_TUNNEL_PROVIDER="$WORK/h-t.prov" CC_BRIDGE_P2P_KEY="$WORK/h.p2p" PATH="$WORK/bin:$PATH" bash "$REPO/claude-bridge" "$@"; }
spoke() { HOME="$SPOKEHOME" CC_BRIDGE_PORT=$SPOKE_PORT CC_BRIDGE_ROOMS_FILE="$WORK/s.rooms" \
          CC_BRIDGE_RENDEZVOUS="http://127.0.0.1:$RDV_PORT" CC_BRIDGE_CODES_FILE="$WORK/s.codes" CC_BRIDGE_ROOM_KEY_FILE="$WORK/s.rk" \
          CC_BRIDGE_SPOKE_PIPE_PID="$WORK/s-p.pid" CC_BRIDGE_SPOKE_PIPE_PORT="$WORK/s-p.port" CC_BRIDGE_SPOKE_PIPE_TICKET="$WORK/s-p.ticket" \
          bash "$REPO/claude-bridge" "$@"; }
cleanup(){ kill "$RDV" 2>/dev/null; kill "$(lsof -ti:$HUB_PORT -sTCP:LISTEN 2>/dev/null|head -1)" 2>/dev/null; kill "$(lsof -ti:$SPOKE_PORT -sTCP:LISTEN 2>/dev/null|head -1)" 2>/dev/null; rm -rf "$WORK"; }
trap cleanup EXIT
codeget(){ jq -r 'keys[0] // empty' "$WORK/h.codes" 2>/dev/null; }

# ── 1. room start with no existing room → auto-create default (password) + open + publish code
OUT=$(hub room start --provider bore 2>&1)
echo "$OUT" | grep -q "created" && ok "room start auto-creates a default room" || bad "no auto-create: $(echo "$OUT"|tail -4)"
echo "$OUT" | grep -qi "ACTIVE — you're hosting" && ok "room start reports ACTIVE" || bad "no ACTIVE line"
echo "$OUT" | grep -q "Room password (shown ONCE" && ok "password generated by default + shown once" || bad "no password shown"
echo "$OUT" | grep -qi "room invite.*one-time\|without sharing the password" && ok "create tip about invite shown" || bad "no invite tip"
DNAME=$(codeget); [ -n "$DNAME" ] && ok "join code auto-published ($DNAME)" || bad "no code published"

# ── 2. status shows ACTIVE hosting
OUT=$(hub status 2>&1)
echo "$OUT" | grep -qi "ACTIVE — you're hosting" && ok "status: owner sees ACTIVE" || bad "status active: $(echo "$OUT"|tail -3)"

# ── 3. room stop → keeps room, releases code, reports paused
OUT=$(hub room stop 2>&1)
echo "$OUT" | grep -qi "paused" && ok "room stop reports paused" || bad "stop: $(echo "$OUT"|tail -3)"
[ -z "$(codeget)" ] && ok "room stop released the join code" || bad "code not released"
OUT=$(hub status 2>&1); echo "$OUT" | grep -qi "PAUSED" && ok "status: shows PAUSED after stop" || bad "status paused: $(echo "$OUT"|tail -3)"

# ── 4. room start again → reopens SAME room (no second create), republishes code
OUT=$(hub room start --provider bore 2>&1)
echo "$OUT" | grep -q "created" && bad "room start re-created instead of reopening" || ok "room start reopens existing room (no re-create)"
[ -n "$(codeget)" ] && ok "code republished on restart" || bad "code not republished"

# ── 5. password join over the real fed listener (direct link; code-resolution
#    itself is covered by test-rendezvous-cli.sh). Set a known password first.
hub room rotate-password testpw123456 >/dev/null 2>&1
OUT=$(spoke join "http://127.0.0.1:${HUB_FED}" --password testpw123456 --node spokeux 2>&1)
echo "$OUT" | grep -qi "joined room" && ok "password join (direct link) works" || bad "pw join: $(echo "$OUT"|tail -4)"
[ "$(cat "$SPOKEHOME/.claude/.cc-bridge-role" 2>/dev/null)" = "spoke" ] && ok "joiner is in spoke role" || bad "spoke role not set"
OUT=$(spoke status 2>&1); echo "$OUT" | grep -qi "In a room" && ok "member status: 'In a room'" || bad "member status: $(echo "$OUT"|tail -3)"

# ── 6. room leave (member)
OUT=$(spoke room leave 2>&1); echo "$OUT" | grep -qi "unlinked\|leav\|standalone" && ok "room leave works" || bad "leave: $(echo "$OUT"|tail -2)"

# ── 7. room delete releases the code + confirms by name
OUT=$(hub room delete wrong 2>&1; true); echo "$OUT" | grep -qi "confirm" && ok "delete needs typed name" || bad "delete guard: $OUT"
RN=$(codeget)
OUT=$(hub room delete "$RN" 2>&1)
echo "$OUT" | grep -qi "deleted" && ok "room delete works" || bad "delete: $OUT"
[ -z "$(codeget)" ] && ok "delete released the join code (no stale code left)" || bad "stale code after delete"

# ── 8. --open room: no password
OUT=$(hub room create openroom --open --provider bore 2>&1)
echo "$OUT" | grep -qi "OPEN room" && ok "--open room announces no-password" || bad "open: $(echo "$OUT"|tail -3)"
hub room delete openroom >/dev/null 2>&1

# ── 9. comma + --all expose/hide (needs a fresh room + a couple sessions; use the API directly)
#    Lightweight: just assert the CLI parses comma + --all without crashing and reports per-name.
hub room create zr --password zrpw12345678 --provider bore >/dev/null 2>&1
OUT=$(hub expose a,b,c 2>&1; true)
echo "$OUT" | grep -c "no active session\|EXPOSED" | grep -q 3 && ok "expose comma-list iterates all 3 names" || bad "comma expose: $(echo "$OUT"|tail -4)"
OUT=$(hub hide --all 2>&1; true)
echo "$OUT" | grep -qi "no active sessions\|HIDDEN" && ok "hide --all handled" || bad "hide --all: $(echo "$OUT"|tail -3)"
hub room delete zr >/dev/null 2>&1

echo ""; echo "test-room-ux: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
